// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

#include <metacity-private/preview-widget.h>

guint metacitysharp_metacity_preview_get_right_width_offset (void);

guint
metacitysharp_metacity_preview_get_right_width_offset (void)
{
	return (guint)G_STRUCT_OFFSET (MetaPreview, right_width);
}

guint metacitysharp_metacity_preview_get_top_height_offset (void);

guint
metacitysharp_metacity_preview_get_top_height_offset (void)
{
	return (guint)G_STRUCT_OFFSET (MetaPreview, top_height);
}

guint metacitysharp_metacity_preview_get_bottom_height_offset (void);

guint
metacitysharp_metacity_preview_get_bottom_height_offset (void)
{
	return (guint)G_STRUCT_OFFSET (MetaPreview, bottom_height);
}

guint metacitysharp_metacity_preview_get_left_width_offset (void);

guint
metacitysharp_metacity_preview_get_left_width_offset (void)
{
	return (guint)G_STRUCT_OFFSET (MetaPreview, left_width);
}

